### ISSUE TITLE
latest version does not start

### ISSUE THREAD

**Issue by yanns** [expert360/docker-elasticmq#5]
We have an error since (I suppose) this commit: https://github.com/expert360/docker-elasticmq/commit/5eaa21c617e0992e8cfa3223a6e9eb7e497d1763

The container cannot start anymore.
```
14:13:31.491 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.12.1) ...
14:13:31.497 [main] ERROR org.elasticmq.server.Main$ - Uncaught exception in thread: main
java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigFactory : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.elasticmq.server.Main$.main(Main.scala:15)
	at org.elasticmq.server.Main.main(Main.scala)
```

**Comment by jbergknoff** [comment]
We're also running into this. Please consider creating proper version tags on Docker Hub so we aren't forced to track the `latest` tag. #2

**Comment by diasjorge** [comment]
I can confirm I'm experiencing the same error

**Comment by CerealBoy** [comment]
@yanns If you required a previous version of the image, [hub now has tags](https://hub.docker.com/r/expert360/elasticmq/tags/) for ``0.9.0``, ``0.9.3``, and ``0.12.1``. You can pin the version you'd prefer now.

**Comment by yanns** [comment]
Great! Thx!

**Comment by yanns** [comment]
the version `0.12.1` still does not start:
```
docker run expert360/elasticmq:0.12.1
09:09:58.626 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.12.1) ...
09:09:58.630 [main] ERROR org.elasticmq.server.Main$ - Uncaught exception in thread: main
java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigFactory : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.elasticmq.server.Main$.main(Main.scala:15)
	at org.elasticmq.server.Main.main(Main.scala)
```

no problem with the version `0.9.3`:
```
docker run expert360/elasticmq:0.9.3
09:12:16.743 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.9.3) ...
09:12:17.102 [elasticmq-akka.actor.default-dispatcher-5] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
09:12:17.581 [main] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:9324, visible server address http://localhost:9324
09:12:17.596 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.9.3) started in 1143 ms ===
```

You may want to switch the java 8 in the docker container:
```
RUN apk --update add openjdk7-jre-base
```
should be changed to java8.

**Comment by CerealBoy** [comment]
@yanns I've rebuilt ``0.12.1`` now with an updated base image for java8, could you please try again?

**Comment by diasjorge** [comment]
I've tried the latest one and it's starting ok

**Comment by yanns** [comment]
@CerealBoy Thx a lot, it's working now:
```
docker run expert360/elasticmq:0.12.1
09:52:52.117 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.12.1) ...
09:52:52.401 [elasticmq-akka.actor.default-dispatcher-3] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
09:52:53.110 [elasticmq-akka.actor.default-dispatcher-6] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:9324, visible server address http://localhost:9324
09:52:53.112 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.12.1) started in 1210 ms ===
```
